### ISSUE TITLE
Consider renaming this repository

### ISSUE THREAD

**Issue by unixorn** [TrooperT/zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but the name is awfully generic. Please consider renaming it to something descriptive, or even just name it after your github username.

Thanks!

**Comment by TrooperT** [comment]
@unixorn I'd be happy to have this added to the collection. I'll see what I can do to update the repo name to "TrooperT-theme"
